### ISSUE TITLE
x/y position doesn't work

### ISSUE THREAD

**Issue by ghost** [Elv13/radical#1]
it doesn't matter if I set position or not result is the same

``` lua
local menu, widget
local function run()
    if not menu then
        menu = radical.context({x=500,y=550})
        widget = wibox.widget.textbox()
        widget:set_markup("Hello World")
        menu:add_widget(widget)
    end
    menu.visible = not menu.visible
end
```

**Comment by chxp82q** [comment]
Thanks for all your work on this menu system, I know its been some time, but the positioning still doesn't work after this fix.
```
menu.x = 100
menu.y = 100
```
This doesn't work either.

**Comment by Elv13** [comment]
Do you have the full code somewhere? Ideally with a screenshot.

It has been a while indeed. Still, technically Radical should still works

**Comment by chxp82q** [comment]
@Elv13 Thanks for the reply! I'm using the code from the readme, putting it in `rc.lua`.
```lua
local radical = require("radical")

---

local menu = radical.context {}

menu.x = 700
menu.y = 700

menu:add_item{
    text = "Screen 1",
    button1 = function(_menu, item, mods) print("Hello World! ") end
}
menu:add_item{text = "Screen 9", icon = beautiful.awesome_icon}
menu:add_item{
    text = "Sub Menu",
    sub_menu = function()
        local smenu = radical.context {}
        smenu:add_item{text = "item 1"}
        smenu:add_item{text = "item 2"}
        return smenu
    end
}
```
I have it change visibility on a right click of the screen.

Here's a preview of the top left corner of my screen:
![gif_2020-09-1702:01:27](https://user-images.githubusercontent.com/33443763/93450178-847a3c00-f88a-11ea-8152-e684aaff0c0d.gif)
